Repository gardener/vpn2, pull requests merged in 2025-01, with the labels that each got.

#123 fix: typo
  README.md
Labels: reviewed/ok-to-test, needs/review, size/xs

#124 Add Dominik Froehlich to CODEOWNERS
  CODEOWNERS
Labels: reviewed/ok-to-test, needs/review, size/xs

#125 Tunnelcontroller for HA: Fix ip6tnl suffix to use two last bytes
  pkg/shoot_client/tunnel/tunnel.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#129 Always listen on both IPv4 and IPv6 sockets on server side.
  pkg/config/vpn-server.go
  pkg/openvpn/assets/server-config.template
  pkg/openvpn/config_server.go
  pkg/openvpn/config_server_test.go
  pkg/vpn_server/values.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s

#130 Deflake broker test
  pkg/ippool/broker.go
  pkg/ippool/broker_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s
